### ISSUE TITLE
Add relevant addresses

### ISSUE THREAD

**Issue by DeveloperInProgress** [IPILabs/shorter-v1-periphery#1]
It would be nice to provide the network addresses of all the contracts in this repo. If you intend to have those addresses only in the docs (https://docs.shorter.finance/getting-started/smart-contracts.html) then, please point me to the address of StrPool contracts  because, I cannot find it in the docs.

**Comment by braady** [comment]
Each StrPool got a separate contract address, you could figure it out on detail page now.
<img width="833" alt="pool address btn" src="https://user-images.githubusercontent.com/43574008/183629338-cff80262-cced-4e26-843c-031b784d4476.png">
